from setuptools import setup, find_packages

setup(
  name = 'general_motion_retargeting',
  packages = find_packages(),
  author="Jenny Jie",
  author_email="jennyjlq2004@gmail.com",
  description="GMR (fork) adapted for the HighTorque MiniPi model",
  long_description=open("README.md").read(),
  long_description_content_type="text/markdown",
  url="https://github.com/0Jen-ny0/RL-minipi",
  license="MIT",
  version="0.2.0",
  install_requires=[
    "loop_rate_limiters",
    "mink",
    "mujoco",
    "numpy",
    "scipy",
    "qpsolvers[proxqp]",
    "rich",
    "tqdm",
    "opencv-python",
    "natsort",
    "psutil",
    "smplx @ git+https://github.com/vchoutas/smplx",
    "protobuf",
    "redis[hiredis]",
    "imageio[ffmpeg]",
  ],
  python_requires='>=3.10',
)
